WebBazzer/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBazzer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.genPromoRights = new HashSet<genPromoRight>();
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string CName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genPromoRight> genPromoRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

WebBazzer/Models/Categorys.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
namespace WebBazzer.Models
{
    [MetadataType(typeof(Categorys))]

    public partial class Category
    {
    }
   
        public class Categorys
        {
            public int Id { get; set; }
            [Required(ErrorMessage = "Please Enter Categry Name")]
            public string  CName { get; set; }
        }
    
}

WebBazzer/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBazzer.Models;
using WebBazzer.BLL;
using System.Data.SqlClient;
using System.Web.Configuration;
using System.Data;
using WebBazzer.Gateway;
using System.Data.Entity;

namespace WebBazzer.Controllers
{
    public class CategoryController : Controller
    {
        WebBazerEntities db = new WebBazerEntities();
        private CategoryManager CategoryManager;
        private LoginController login;
        string connectionString = WebConfigurationManager.ConnectionStrings["WebBazer"].ConnectionString;
        public CategoryController()
        {
            //if(Session["login"]==null)
            //{
            //    //redirect to logincontroller
            //}
            CategoryManager = new CategoryManager();
        }
        [HttpGet]
        public ActionResult Index()
        {

            //return View(db.Categories.ToList());
            DataTable dtblProduct = new DataTable();
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("SELECT * FROM Category", sqlCon);
                sqlDa.Fill(dtblProduct);
            }
            return View(dtblProduct);
        }

        public ActionResult Save()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Save(Categorys category)
        {
            if (ModelState.IsValid)
            {
                string message = CategoryManager.Save(category);
                ViewBag.Message = message;
                ModelState.Clear();
                return RedirectToAction("Index");
            }
            else
            {
                string message = "Model State is Invalid";
                return RedirectToAction("Index");
            }

        }

        
         //GET: /Product/Edit/5
        public ActionResult Edit(int id)
        {
            Category category = new Category();
            DataTable dtblProduct = new DataTable();
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "SELECT * FROM Category Where Id = @id";
                SqlDataAdapter sqlDa = new SqlDataAdapter(query, sqlCon);
                sqlDa.SelectCommand.Parameters.AddWithValue("@id", id);
                sqlDa.Fill(dtblProduct);
            }
            if (dtblProduct.Rows.Count == 1)
            {
                category.Id = Convert.ToInt32(dtblProduct.Rows[0][0].ToString());
                category.CName = dtblProduct.Rows[0][1].ToString();

                return View(category);
            }
            else
                return RedirectToAction("Index");
        }

        //
        // POST: /Product/Edit/5
        [HttpPost]
        public ActionResult Edit(Category category)
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "UPDATE Category SET CName=@name WHere Id = @id";
                SqlCommand sqlCmd = new SqlCommand(query, sqlCon);
                sqlCmd.Parameters.AddWithValue("@id", category.Id);
                sqlCmd.Parameters.AddWithValue("@name", category.CName);
                sqlCmd.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }

      //  [HttpGet]
        //public ActionResult Edit(int id)
        //{
        //    Category category = db.Categories.Single(x => x.Id == id);
        //    if (category == null)
        //    {
        //        return HttpNotFound();
        //    }
           
        //    return View("Edit", category);
        //}

        ////Post Edit
        //[HttpPost]
        //public ActionResult Edit(Category category)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(category).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index", "Product");
        //    }

        //    return View(category);
        //}


        public ActionResult Delete(int id)
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "DELETE FROM Category WHere Id = @id";
                SqlCommand sqlCmd = new SqlCommand(query, sqlCon);
                sqlCmd.Parameters.AddWithValue("@id", id);
                sqlCmd.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }
        //public ActionResult Delete(int id)
        //{
        //    Category category = db.Categories.Find(id);
        //    if (category == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(category);

        //}

        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Category category = db.Categories.Find(id);
        //    db.Categories.Remove(category);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    base.Dispose(disposing);
        //}

        //public ActionResult Details(int id)
        //{
        //    Category category = db.Categories.Find(id);
        //    if (category == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(category);
        //}

    }
}

WebBazzer/Views/Category/Edit.cshtml
@model WebBazzer.Models.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    #errmsg {
        color: red;
        position:center;
    }

    .field-validation-error {
        margin-left: 140px;
        color: red;
    }

    #wrapper {
        width: 50%;
        margin: 0 auto;
    }

    input {
        width: 240px;
        position:page;
    }

    #message {
        color: red;
        font: bolder;
        font-family: fantasy;
        font-size: larger;
        font-style: italic;
        font-feature-settings: on;
    }
    Label{
         color: red;
        font: bolder;
        font-feature-settings: on;
        position:center;
    }
    
</style>

<div id="wrapper">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="single-product-tab-area mg-b-30">
            <br />
            <br />
            <br />
            <br />
            <div class="input-group mg-b-pro-edt">
                <span class="input-group-addon" style="color:white; font-size:xx-large;position:relative;font-weight:bolder"><i class="icon nalika-home icon-wrap" aria-hidden="true"></i>Update Category</span>
            </div>
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)

            <div class="input-group mg-b-pro-edt">
                <br />
                @Html.LabelFor(model => model.CName, new { @class = "form-control" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CName, new { htmlAttributes = new { @class = "form-control"} })
                    <br />
                    @Html.ValidationMessageFor(model => model.CName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="input-group mg-b-pro-edt">
                <input type="submit" value="Update" id="submit" class="btn btn-success" />
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    </div >
@section Scripts {
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

}

WebBazzer/Views/Category/Index.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Index";
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    /*#wrapper {
        width: 400px;
        margin: 0 auto;
    }
    table {
        border-collapse: collapse;
        width: 100%;
    }
    th, td {
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }*/

    th {
        background-color: skyblue;
        color: white;
    }
</style>

<div class="wrapper">
    <br />
    <br />
    <br />
    <br />
   
    <div class="input-group mg-b-pro-edt">
        <span class="input-group-addon" style="color:white; font-size:xx-large;position:relative;font-weight:bolder"><i class="icon nalika-home icon-wrap" aria-hidden="true"></i>All Category</span>
       
    </div>
    <div class="product-status mg-b-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <table>
                            <tr>
                                <th>Name</th>

                                <th>Action</th>
                            </tr>

                            @for (int i = 0; i < Model.Rows.Count; i++)
                            {
                                <tr>
                                    <td>@Model.Rows[i][1]</td>

                                    <td>
                                        <a href="@Url.Action("Edit", "Category", new {@id=@Model.Rows[i][0] })">Edit</a>
                                        <a href="@Url.Action("Delete", "Category", new {@id=@Model.Rows[i][0] })">Delete</a>
                                    </td>
                                </tr>
                            }
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>

   

</div>

WebBazzer/Views/Category/Save.cshtml
@model WebBazzer.Models.Categorys

@{
   
    ViewBag.Title = "Category";
    ViewBag.SubTitle = "Save";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #errmsg {
        color: red;
    }

    .field-validation-error {
        margin-left: 140px;
        color: red;
    }

    #wrapper {
        width: 50%;
        margin: 0 auto;
        
    }

    input {
        width: 240px;
    }
    h1{
        color:red;
        text-decoration-color:red;
        font:bolder;
        font-size:xx-large;
        font-feature-settings:on;
        
    }
</style>

    #message {
        color: red;
        font: bolder;
        font-family: fantasy;
        font-size: larger;
        font-style: italic;
        font-feature-settings: on;
    }
   
</style>
<h1>Save</h1>

<div id="wrapper">
    @using (Html.BeginForm("Save", "Category", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="single-product-tab-area mg-b-30">
            <br />
            <br />
            <br />
            <br />
            <div class="input-group mg-b-pro-edt">
                <span class="input-group-addon" style="color:white; font-size:xx-large;position:relative;font-weight:bolder"><i class="icon nalika-home icon-wrap" aria-hidden="true"></i>Save Category</span>
            </div>
            <div class="input-group mg-b-pro-edt">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <span class="input-group-addon"><i class="icon nalika-user" aria-hidden="true"></i></span>
                @*@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })*@

                @Html.EditorFor(model => model.CName, new { htmlAttributes = new { @class = "form-control", placeholder = "Category Name" } })
                @Html.ValidationMessageFor(model => model.CName, "", new { @class = "text-danger" })
            </div>

            <div class="input-group mg-b-pro-edt">
                <input type="submit" value="Save" id="submit" class="btn btn-success"  />
            </div>
            
        </div>


    }
    @if (ViewBag.Message != null)
    {
        <h3>@ViewBag.Message</h3>
    }
</div>
@section Scripts {
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

}