WebBazzer/Models/Wishlist.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBazzer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int ProductID { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Coustomer Coustomer { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}

WebBazzer/Controllers/WishListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBazzer.Models;

namespace WebBazzer.Controllers
{
    public class WishListController : Controller
    {
        WebBazerEntities db = new WebBazerEntities();
        // GET: WishList
        public ActionResult Index()
        {
            this.GetDefaultData();

            var wishlistProducts = db.Wishlists.Where(x => x.CustomerID == TempShpData.UserID).ToList();
            return View(wishlistProducts);
        }
        //REMOVE ITEM FROM WISHLIST
        public ActionResult Remove(int id)
        {
            db.Wishlists.Remove(db.Wishlists.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        //ADD TO CART WISHLIST
        public ActionResult AddToCart(int id)
        {
            OrderDetail OD = new OrderDetail();

            int pid = db.Wishlists.Find(id).ProductID;
            OD.ProductID = pid;
            int Qty = 1;
            decimal? price = db.Products.Find(pid).Price;
            OD.Quantity = Qty;
            OD.UnitPrice = price;
            OD.TotalAmount = Qty * price;
            OD.Product = db.Products.Find(pid);

            if (TempShpData.items == null)
            {
                TempShpData.items = new List<OrderDetail>();
            }
            TempShpData.items.Add(OD);

            db.Wishlists.Remove(db.Wishlists.Find(id));
            db.SaveChanges();

            return Redirect(TempData["returnURL"].ToString());

        }
    }
}

WebBazzer/Views/WishList/Index.cshtml
@model IEnumerable<WebBazzer.Models.Wishlist>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutFont.cshtml";
}

<!-- catg header banner section -->
<section id="aa-catg-head-banner">
    <img src="~/Content/img/fashion/fashion-header-bg-8.jpg" alt="fashion img">
    <div class="aa-catg-head-banner-area">
        <div class="container">
            <div class="aa-catg-head-banner-content">
                <h2>Wishlist Page</h2>
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Wishlist</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- / catg header banner section -->
<!-- Cart view section -->
<section id="cart-view">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="cart-view-area">
                    <div class="cart-view-table aa-wishlist-table">
                        <form action="">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th></th>
                                            <th>Product</th>
                                            <th>Price</th>
                                            <th>Stock Status</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Session["username"] != null)
                                        {
                                            foreach (var item in Model)
                                            {

                                                <tr>
                                                    <td><a class="remove" href="@Url.Action("Remove", "WishList", new { id=item.ID})"><fa class="fa fa-close"></fa></a></td>
                                                    <td><a href="#"><img src="@item.Product.ImageUrl" ></a></td>
                                                    <td><a class="aa-cart-title" href="#">@item.Product.PName</a></td>
                                                    <td>@item.Product.Price</td>
                                                    <td>
                                                        @if (item.Product.AvailableQuantity > 0)
                                                        {
                                                            <text>In Stock (@item.Product.AvailableQuantity)</text>
                                                        }
                                                        else
                                                        { <text>Out of Stock (@item.Product.AvailableQuantity)</text>}
                                                    </td>
                                                    <td><a href="@Url.Action("AddToCart", "WishList", new { id=item.ID})" class="aa-add-to-cart-btn">Add To Cart</a></td>
                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <text>Please login to view wishlist</text>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / Cart view section -->