WebBazzer/Models/Supplier.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBazzer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string MobileNo { get; set; }
        public string ImageUrl { get; set; }
    }
}

WebBazzer/Models/Suppliers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebBazzer.Models
{
    [MetadataType(typeof(Supplier))]
    public partial class Supplier
    {
    }
    public class Suppliers
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please Enter First Name")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Name contains only Alphabets")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please Enter Last Name")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Name contains only Alphabets")]
        public string LastName { get; set; }
         [Required(ErrorMessage = "Please Enter A Email")]
         [DataType(DataType.EmailAddress, ErrorMessage = "Please enter correct email address")]
        public string Email { get; set; }
         [Required(ErrorMessage = "Please Enter Age")]
        
        public int Age { get; set; }
        [Required(ErrorMessage = "Please Enter Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Select Gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please Enter A Mobile No")]
        [DataType(DataType.PhoneNumber, ErrorMessage = "Please enter correct mobile No")]
        public string MobileNo { get; set; }
        public string ImageUrl { get; set; }
        [Required(ErrorMessage = "Please Select A Image")]
        [DataType(DataType.Upload, ErrorMessage = "Please Select A Image")]
        public HttpPostedFileBase FileName { get; set; }

    }
}

WebBazzer/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBazzer.Models;
using WebBazzer.BLL;
using System.Configuration;
using System.IO;
using System.Data;
using System.Drawing;
using System.Web.Configuration;
using System.Data.SqlClient;

namespace WebBazzer.Controllers
{
    public class SupplierController : Controller
    {
        string connectionString = WebConfigurationManager.ConnectionStrings["WebBazer"].ConnectionString;
        SupplierManager SupplierManager;
        public SupplierController()
        {
            SupplierManager = new SupplierManager();
        }
        public ActionResult Index()
        {
            DataTable dtblProduct = new DataTable();
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("SELECT * FROM Supplier", sqlCon);
                sqlDa.Fill(dtblProduct);
            }
            return View(dtblProduct);
        }
        public ActionResult Save()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Save(Suppliers supplier)
        {
            var fileName = Path.GetFileNameWithoutExtension(supplier.FileName.FileName);
            
            var extention = Path.GetExtension(supplier.FileName.FileName);


            string path = Path.Combine(Server.MapPath("~/ProductImageFile/"), fileName + extention);
            supplier.ImageUrl = path;
            supplier.FileName.SaveAs(path);
                string message = SupplierManager.Save(supplier);
                ViewBag.Message = message;
                ModelState.Clear();
            
            return View();
        }

        public ActionResult Edit(int id)
        {
            Suppliers supplier = new Suppliers();
            DataTable dtblProduct = new DataTable();
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "SELECT * FROM Supplier Where Id = @id";
                SqlDataAdapter sqlDa = new SqlDataAdapter(query, sqlCon);
                sqlDa.SelectCommand.Parameters.AddWithValue("@id", id);
                sqlDa.Fill(dtblProduct);
            }
            if (dtblProduct.Rows.Count == 1)
            {
                supplier.Id = Convert.ToInt32(dtblProduct.Rows[0][0].ToString());
                supplier.FirstName = dtblProduct.Rows[0][1].ToString();
                supplier.LastName = dtblProduct.Rows[0][2].ToString();
                supplier.Email = dtblProduct.Rows[0][3].ToString();
                supplier.Age = Convert.ToInt32(dtblProduct.Rows[0][4].ToString());
                supplier.Address = dtblProduct.Rows[0][5].ToString();
                supplier.Gender = dtblProduct.Rows[0][6].ToString();
                supplier.MobileNo = dtblProduct.Rows[0][7].ToString();
                supplier.ImageUrl = dtblProduct.Rows[0][8].ToString();
                return View(supplier);
            }
            else
                return RedirectToAction("Index");
        }
         [HttpPost]
        public ActionResult Edit(Suppliers supplier)
        {
            //ViewBag.Category = CategoryManager.GetSelectListItemsForDropdown();
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "UPDATE  Supplier SET FirstName=@firstName,LastName=@lastName,Email=@email,Age=@age,Address=@address,Gender=@gender,MobileNo=@mobileNo,ImageUrl=@imageUrl WHERE Id=@id";
                SqlCommand Command = new SqlCommand(query, sqlCon);
                Command.Parameters.AddWithValue("@id", supplier.Id);
                Command.Parameters.AddWithValue("@firstName", supplier.FirstName);
                Command.Parameters.AddWithValue("@lastName", supplier.LastName);
                Command.Parameters.AddWithValue("@email", supplier.Email);
                Command.Parameters.AddWithValue("@age", supplier.Age);
                Command.Parameters.AddWithValue("@address", supplier.Address);
                Command.Parameters.AddWithValue("@gender", supplier.Gender);
                Command.Parameters.AddWithValue("@mobileNo", supplier.MobileNo);
                Command.Parameters.AddWithValue("@imageUrl", supplier.ImageUrl);
                Command.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "DELETE FROM Supplier WHere Id = @id";
                SqlCommand sqlCmd = new SqlCommand(query, sqlCon);
                sqlCmd.Parameters.AddWithValue("@id", id);
                sqlCmd.ExecuteNonQuery();
            }
            return RedirectToAction("Index");
        }
      
	}
}

WebBazzer/Views/Supplier/Edit.cshtml
@model WebBazzer.Models.Suppliers

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Supplier</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age)
                @Html.ValidationMessageFor(model => model.Age)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobileNo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobileNo)
                @Html.ValidationMessageFor(model => model.MobileNo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender)
                @Html.ValidationMessageFor(model => model.Gender)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl)
                @Html.ValidationMessageFor(model => model.ImageUrl)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebBazzer/Views/Supplier/Index.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    /*#wrapper {
        width: 400px;
        margin: 0 auto;
    }
    table {
        border-collapse: collapse;
        width: 100%;
    }
    th, td {
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }*/

    th {
        background-color: skyblue;
        color: white;
    }
</style>

<div class="wrapper">
    <br />
    <br />
    <br />
    <br />

    <div class="input-group mg-b-pro-edt">
        <span class="input-group-addon" style="color:white; font-size:xx-large;position:relative;font-weight:bolder"><i class="icon nalika-home icon-wrap" aria-hidden="true"></i>All Supplier</span>

    </div>
    <div class="product-status mg-b-30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap">
                        <table>
                            <tr>
                                <th>Image</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Age</th>
                                <th>Address</th>
                                <th>Gender</th>
                                <th>Mobile No</th>
                                <th>Action</th>
                               
                            </tr>

                            @for (int i = 0; i < Model.Rows.Count; i++)
                            {
                                <tr>
                                    <td><img src="@Model.Rows[i][8]" alt="Alternate Text" /></td>
                                    <td>@Model.Rows[i][1]</td>
                                    <td>@Model.Rows[i][2]</td>
                                    <td>@Model.Rows[i][3]</td>
                                    <td>@Model.Rows[i][4]</td>
                                    <td>@Model.Rows[i][5]</td>
                                    <td>@Model.Rows[i][6]</td>
                                    <td>@Model.Rows[i][7]</td>

                                    <td>
                                        <a href="@Url.Action("Edit", "Supplier", new {@id=@Model.Rows[i][0] })">Edit</a>
                                        <a href="@Url.Action("Delete", "Supplier", new {@id=@Model.Rows[i][0] })">Delete</a>
                                    </td>
                                </tr>
                            }
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>



</div>

WebBazzer/Views/Supplier/Save.cshtml
@model WebBazzer.Models.Suppliers
@{

    Layout = null;
    ViewBag.Title = "Save";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <title></title>

</head>
<style>
    #errmsg {
        color: red;
    }

    .field-validation-error {
        margin-left: 140px;
        color: red;
    }

    #wrapper {
        width: 50%;
        margin: 0 auto;
    }

    input {
        width: 240px;
    }

    #message {
        color: red;
        font: bolder;
        font-family: fantasy;
        font-size: larger;
        font-style: italic;
        font-feature-settings: on;
    }
    
</style>



<div id="wrapper">
    @using (Html.BeginForm("Save", "Supplier", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        @Html.AntiForgeryToken()
        <div class="single-product-tab-area mg-b-30">
            <br />
            <br />
            <br />
            <br />
            <div class="input-group mg-b-pro-edt">
                <span class="input-group-addon" style="color:white; font-size:xx-large;position:relative;font-weight:bolder"><i class="icon nalika-home icon-wrap" aria-hidden="true"></i>Save Supplier</span>
            </div>
    <div class="input-group mg-b-pro-edt">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <span class="input-group-addon"><i class="icon nalika-user" aria-hidden="true"></i></span>
        
            @Html.TextBoxFor(model => model.FirstName ,new { id = "FirstName", @class = "form-control", placeholder = "First Name" })
            @Html.ValidationMessageFor(model => model.FirstName)
       
    </div>

    <div class="input-group mg-b-pro-edt">
     
        <span class="input-group-addon"><i class="icon nalika-user" aria-hidden="true"></i></span>
           @Html.TextBoxFor(model => model.LastName ,new { id = "LastName", @class = "form-control", placeholder = "Last Name" })
            @Html.ValidationMessageFor(model => model.LastName)

    </div>

    <div class="input-group mg-b-pro-edt">
        <span class="input-group-addon"><i class="icon nalika-mail" aria-hidden="true"></i></span>
            @Html.TextBoxFor(model => model.Email,new { id = "Email", @class = "form-control", placeholder = "Email" })
            @Html.ValidationMessageFor(model => model.Email)
        
    </div>

    <div class="input-group mg-b-pro-edt">
        <span class="input-group-addon"><i class='icon nalika-unlocked' aria-hidden="true"></i></span>
        @Html.TextBoxFor(model => model.Age, new { id = "Age", @class = "form-control", placeholder = "Age" })
        @Html.ValidationMessageFor(model => model.Age)

    </div>

    <div class="input-group mg-b-pro-edt">
        <span class="input-group-addon"><i class='icon nalika-info' aria-hidden="true"></i></span>
        @Html.TextBoxFor(model => model.Address, new { id = "Address", @class = "form-control", placeholder = "Address" })
        @Html.ValidationMessageFor(model => model.Address)

    </div>

    <div class="input-group mg-b-pro-edt">
        <span class="input-group-addon"><i class='fa fa-phone' aria-hidden="true"></i></span>
        @Html.TextBoxFor(model => model.MobileNo, new { id = "MobileNo", @class = "form-control", placeholder = "Mobile No" })
        @Html.ValidationMessageFor(model => model.MobileNo)

    </div>

    <div class="input-group mg-b-pro-edt">
        <span class="input-group-addon"><i class='fa fa-intersex' aria-hidden="true"></i></span>
        @Html.DropDownList("Gender", new List<SelectListItem>
        {
        	new SelectListItem{ Text="Male", Value="Male"},
        	new SelectListItem{ Text="Female", Value="Female"},
            new SelectListItem{ Text="Other", Value="Other"}
		}, "--- Select Gender ---", new { @class = "form-control pro-edt-select form-control-primary" })
        @Html.ValidationMessageFor(model => model.Gender)

    </div>

    <div class="input-group mg-b-pro-edt">
       
        <span class="input-group-addon"><i class="icon nalika-picture" aria-hidden="true"></i></span>
        @Html.TextBoxFor(x => x.FileName, new { type = "file", id = "BSbtninfo", @class = "custom-file-input", Value = "Upload Image" })
        
        @Html.ValidationMessageFor(x => x.FileName)
    </div>

    <div class="input-group mg-b-pro-edt">

        <input type="submit" value="Save" id="submit" class="btn btn-ctl-bt waves-effect waves-light m-r-10" />
        

    </div>
    </div>
    }
    @if (ViewBag.Message != null)
    {


        <p id="message">@ViewBag.Message</p>
    }

</div>

@section Scripts {
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Content/Scripts/FileUpload.js"></script>

    <script type="text/javascript">
        $('#BSbtninfo').filestyle({
            buttonName: 'btn-info',
            buttonText: ' Select a Image File'
        });
    @*$(document).ready(function () {

        $("#CategoryId").change(function () {
            var CategoryId = $("#CategoryId").val();

            var json = { categoryId: CategoryId };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetSubCategory","Product")',

                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $("#SubCategoryId").empty();
                    $("#SubCategoryId").append('<option value="">--Select--</option>');
                    $.each(data, function (key, value) {
                        $("#SubCategoryId").append('<option value=' + value.SubCategoryId + '>' + value.SubCategory + '</option>');

                    });

                }
            });
        });
    });*@
    </script>
}